# This is a basic workflow that is manually triggered

name: login-yahoo-manual

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  [workflow_dispatch]

concurrency:
  group: login-and-schedule
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "login"
  login:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          - name: Checkout repo content
            uses: actions/checkout@v3       # checkout the repository content to github runner.
            with:
              token: ${{ secrets.WORKFLOW_TOKEN }}
          - name: Setup Python
            uses: actions/setup-python@v2
            with:
                python-version: 3.9.6
          - name: Setup dependencies
            run: |
              pip install python-dotenv
              pip install playwright
              playwright install firefox
              pip install pandas
          - name: Clone private repo folder
            env:
              WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
            run: |
              git clone \
              --depth 1 \
              --filter=blob:none \
              --sparse \
              https://$WORKFLOW_TOKEN@github.com/schmwong/login-log \
              ;
              cd login-log
              git sparse-checkout init --cone
              git sparse-checkout set yahoo
              cd ..
          - name: Run Python script
            run: |
              export USR_YAHOO_1=${{ secrets.USR_YAHOO_1 }}
              export PWD_YAHOO_1=${{ secrets.PWD_YAHOO_1 }}
              python keep-yahoo-active.py 
          - name: Commit and push folder to private repo if updated
            env:
              WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
            run: |
              cd login-log
              datestamp=$(date -u +%F)
              git config user.name "${GITHUB_ACTOR}"
              git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
              git add ./yahoo
              if ! git diff-index --quiet HEAD; then
                git commit -m "updated Yahoo logs for ${datestamp} (manual)" -- ./yahoo 
                git push "https://${GITHUB_ACTOR}:$WORKFLOW_TOKEN@github.com/schmwong/login-log.git" \
                HEAD:main || exit 0
              fi
